fix: snic: Fix compilation error when using gcc-5.3
This error is caused by ambiguity in evaluating the different
parts of a compound statement.
See: http://stackoverflow.com/questions/21625554/warning-operation-on-variable-may-be-undefined

Change-Id: Ie0db658710a5288970714e41cd7e5fcee9d636d9
Signed-off-by: Shadi Ammouri <shadi@marvell.com>
Reviewed-on: http://vgitil04.il.marvell.com:8080/38290
Tested-by: iSoC Platform CI <ykjenk@marvell.com>
Reviewed-by: Yehuda Yitschak <yehuday@marvell.com>
(cherry picked from commit c17a579d63cda25287743082b60656904d3743ef)
Reviewed-on: http://vgitil04.il.marvell.com:8080/38337
Reviewed-by: Yuval Caduri <cyuval@marvell.com>
Reviewed-on: http://vgitil04.il.marvell.com:8080/38622
Tested-by: Yuval Caduri <cyuval@marvell.com>